### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RyanTheAllmighty** [RyanTheAllmighty/Allmighty-Twitch-Toolbox#2]
This is a list of the things I wish to get done and add to the program:
- [ ] Add in [AllmightyBot](https://www.github.com/RyanTheAllmighty/AllmightyBot) to the application.
- [x] Add in a mute tool to allow muting and unmuting of a set microphone or possibly of just OBS on a keybind.
- [x] Add in overlays which are just overlays with different information presented and updated on them which cover a 1280x720 source in OBS.
- [x] Add in alerts for hosting of the channel.
- [ ] Add in a scene that shows the chat, not from Twitch.tv but created custom and stylable.
